#!/usr/bin/env python3
"""Generate claude/crab.generated.css — the greeting pixel sparkle.

WHAT THIS FILE STILL DRAWS, AND WHY SO LITTLE
The skin used to draw Clawd itself, as a CSS ::after pseudo-element on the
composer. That crab is gone: the interactive crab now lives in crab-plugin/,
which mounts a real element and carries its own copy of the pixel frames. Two
carriers meant two sources of truth and three separate "two crabs / no crab"
bugs, so the skin no longer draws a crab at all.

What remains is the small pixel sparkle that floats beside the greeting on an
empty session. It is not the mascot, it does not overlap the composer, and it
has no interactive counterpart — so it stays here, in the skin.

Removing the composer crab also removed the 15 embedded frame variables
(~46 KB, 84% of this file): only the crab's own placements ever read them.

Geometry credit for the Clawd mascot: lulu (github.com/claudenoshujin/claude-web).
See the repository LICENSE.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'claude' / 'crab.generated.css'

css = """/* ============================================================================
 * Greeting pixel sparkle
 *
 * GENERATED by scripts/gen-crab.py — do not hand-edit.
 *
 * One 3x3px dot replicated by `box-shadow`. No image, no request, no asset
 * weight. It sits beside the greeting on an empty session.
 *
 * The composer crab is NOT drawn here: that is crab-plugin/, which mounts a
 * real element so it can be clicked. See this file's generator for the history.
 * ========================================================================== */

:root {
  --cl-spark: #141413;
}

body[data-ds-dark-theme] {
  --cl-spark: #faf9f5;
}

[data-slot="conversation.hero.brand.mark"] {
  position: relative;
}

[data-slot="conversation.hero.brand.mark"]::after {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  width: 3px;
  height: 3px;
  background: transparent;
  pointer-events: none;
  box-shadow:
    39px 0 0 var(--cl-spark), 42px 0 0 var(--cl-spark), 45px 0 0 var(--cl-spark),
    45px 3px 0 var(--cl-spark), 42px 6px 0 var(--cl-spark),
    21px 12px 0 var(--cl-spark), 27px 12px 0 var(--cl-spark),
    33px 12px 0 var(--cl-spark), 42px 12px 0 var(--cl-spark);
  animation: cl-spark-float 2.83s cubic-bezier(.37,0,.22,1) .41s infinite;
}

@keyframes cl-spark-float {
  0%, 100% { transform: translateY(0);    opacity: .8; }
  50%      { transform: translateY(-4px); opacity: 1; }
}

@media (prefers-reduced-motion: reduce) {
  [data-slot="conversation.hero.brand.mark"]::after { animation: none; }
}
"""

OUT.write_text(css, encoding='utf-8')
print(f"wrote {OUT} ({len(css)} bytes)")

# The manifest admits exactly two stylesheets (stylesheet + patches), so the
# generated section is appended to the hand-written selector layer to form the
# served patches.css. patches.base.css is the hand-written input; never edit
# patches.css directly.
base = ROOT / 'claude' / 'patches.base.css'
final = ROOT / 'claude' / 'patches.css'
final.write_text(base.read_text(encoding='utf-8').rstrip() + "\n\n" + css, encoding='utf-8')
print(f"composed {final} ({len(final.read_text(encoding='utf-8'))} bytes) = patches.base.css + sparkle")
