#!/usr/bin/env python3
"""Generate claude/crab.css — the Clawd pixel crab, ported to DSH.

The crab is NOT an image: it is pure CSS `box-shadow` pixel art (one 3x3px
element whose shadow list paints every pixel). We re-derive it from the
reference implementation's frame data so the port is exact rather than
approximated, then re-colour it through our own tokens.

Source of the frame geometry: the SillyTavern "Claude Web 2.0" extension by
lulu (github.com/claudenoshujin/claude-web), distributed freely in the 类脑
community. Credit for the original pixel artwork belongs to that author.

We reuse the *pixel geometry* only. All selectors, keyframes, colour mapping
and placement in this file are original to this project, and no file from that
repository is copied.
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
REF = pathlib.Path('/tmp/clawd-frames.json')
OUT = ROOT / 'claude' / 'crab.generated.css'

CELL = 3          # px per pixel-art cell
EYE = 'var(--cl-crab-eye)'
BODY = 'var(--cl-crab-body)'

def parse(value: str):
    """-> list[(x_px, y_px, colour)] for one reference frame."""
    out = []
    for part in value.split(','):
        part = ' '.join(part.split())
        m = re.match(r'^(-?[\d.]+)px\s+(-?[\d.]+)px\s+0\s+[\d.]+px\s+(#[0-9a-fA-F]+|var\([^)]+\))$', part)
        if m:
            out.append((float(m.group(1)), float(m.group(2)), m.group(3)))
    return out


# The crab art is anchored so its top-left pixel sits at the element origin.
# Without this, every frame inherits the reference's arbitrary negative offsets
# (left:-4px / top:-14px on a different host element) and lands in the wrong
# place — which is exactly how the first port came out mis-sized and mis-placed.
_anchor = None


def anchor(frames_map):
    """Minimal x/y across all frames, so every frame shares one origin."""
    xs, ys = [], []
    for v in frames_map.values():
        for x, y, _ in parse(v):
            xs.append(x); ys.append(y)
    return min(xs), min(ys)


def port(value: str) -> str:
    """Rewrite a reference frame into our token-driven, origin-anchored shadow list."""
    ax, ay = _anchor
    out = []
    for x, y, colour in parse(value):
        c = EYE if 'clawd-eye' in colour else BODY
        out.append(f'{x - ax:g}px {y - ay:g}px 0 .3px {c}')
    return ', '.join(out)

frames = json.loads(REF.read_text())
want = {
    'open': '--clawd-f-open',
    'blink': '--clawd-f-blink',
    'look-u': '--clawd-f-look-u',
    'look-d': '--clawd-f-look-d',
    'look-l': '--clawd-f-look-l',
    'look-r': '--clawd-f-look-r',
    'shut': '--clawd-f-shut',
    'cheer': '--clawd-f-cheer',
    'cheer-mid': '--clawd-f-cheer-mid',
    'tucked': '--clawd-f-tucked',
    'tucked-blink': '--clawd-f-tucked-blink',
}

_anchor = anchor(frames)

# Art extent in px, derived from the anchored data (cell = CELL px per pixel).
_all = [p for v in frames.values() for p in parse(v)]
ART_W = (max(x for x, _, _ in _all) - _anchor[0]) + CELL
ART_H = (max(y for _, y, _ in _all) - _anchor[1]) + CELL

blocks = []
for name, key in want.items():
    if key in frames:
        blocks.append(f'  --crab-f-{name}: {port(frames[key])};')

css = f"""/* ============================================================================
 * Clawd — the Claude Code pixel crab
 *
 * GENERATED by scripts/gen-crab.py — do not hand-edit.
 *
 * The crab is pure CSS: one {CELL}x{CELL}px element whose `box-shadow` list
 * paints every pixel. No image, no font, no request — so it stays crisp, inherits
 * our colour tokens, and costs zero asset weight.
 *
 * Clawd is Anthropic's mascot for Claude Code. The pixel geometry is
 * reproduced from the reference implementation; all selectors, animation and
 * placement below are ours.
 * ========================================================================== */

:root {{
  --cl-crab-body: #d97757;
  --cl-crab-eye: #141413;
  /* Cell size is {CELL}px in the source data; scaling is done by transform so
     the shadow geometry never has to be recomputed. */
  --cl-crab-cell: {CELL}px;
  /* Art extent, derived from the anchored frame data. Every placement below
     positions against these, never against hand-measured numbers. */
  --cl-crab-w: {ART_W:g}px;
  --cl-crab-h: {ART_H:g}px;
  /* Composer crab is the reference's 36x24-ish footprint. 1 = native size. */
  --cl-crab-k: .85;
}}

body[data-ds-dark-theme] {{
  --cl-crab-body: #d97757;
  --cl-crab-eye: #181715;
}}

/* ---- frame data ---------------------------------------------------------- */
:root {{
{chr(10).join(blocks)}
}}

/* ---------------------------------------------------------------------------
 * Placement.
 *
 * The element itself is ONE cell (3x3px, transparent); the box-shadow paints
 * the art starting at that element's origin and extending right/down by
 * --cl-crab-w / --cl-crab-h. So every placement below positions the ELEMENT ORIGIN,
 * and scales with transform-origin:0 0 so the arithmetic stays true.
 *
 * That is why the crab must be anchored at pixel (0,0) in gen-crab.py: an
 * un-anchored port inherits the reference's offsets, which were measured
 * against a different host element, and lands mis-sized and off-edge.
 * ------------------------------------------------------------------------- */

/* The shared pixel element. */
/* NOTE: `top`/`left` are deliberately NOT set here. Each placement below owns
 * its own coordinates, and [data-composer-card]::after is repositioned further
 * down with an explicit negative `top`. Setting coordinates in this shared rule
 * would make the result depend on source order — a silent failure the moment
 * anything reorders these blocks. Only geometry-neutral properties live here. */
.cl-crab,
[data-composer-card]::after,
[data-slot="conversation.hero.brand.mark"]::after,
.cl-greeting-particles::after {{
  content: '';
  position: absolute;
  width: {CELL}px;
  height: {CELL}px;
  background: transparent;
  pointer-events: none;
  transform-origin: 0 0;
}}

/* ---- A. Composer crab -----------------------------------------------------
 * Stands ON the composer's top edge, right-aligned, at all times; while a
 * turn streams it bobs instead of merely blinking.
 * Non-interactive by construction: it is a pseudo-element, so it is not
 * focusable, not clickable, and needs no creation or cleanup code. The
 * reference makes the same choice deliberately — a mascot that looks clickable
 * but is not reads worse than one that plainly is not.
 * ------------------------------------------------------------------------- */
[data-composer-card] {{
  position: relative;
  overflow: visible;
}}

[data-composer-card]::after {{
  /* POSITIONING IS EXPLICIT ON PURPOSE.
   *
   * The art is drawn DOWNWARD from the element's origin by box-shadow, so
   *     art_bottom = element_top + (art_height * scale)
   * and the crab stands on the line when that equals the card's outer top edge:
   *     top = -(art_height * scale) - 1px     (-1px sinks it onto the border)
   *
   * An earlier version used `bottom: 100%` plus `transform: translateY(-100%)`,
   * which is relative to the element's OWN height. If that height ever fails to
   * apply, the percentage collapses to zero and the art is painted downward
   * INTO the card — the crab appears inside the input box. Explicit values
   * cannot fail that way. */
  top: calc(-1 * var(--cl-crab-h) * var(--cl-crab-k) - 1px);
  bottom: auto;
  left: auto;
  right: 32px;
  box-shadow: var(--crab-f-open);
  transform: scale(var(--cl-crab-k));
  /* Always present: the crab is company, not a progress spinner. It idles on
     the composer edge and only ADDS the bob while a turn is streaming, so it
     is visible in a normal session rather than only mid-generation. */
  opacity: .9;
  animation: crab-idle-frames 3s step-end infinite;
  transition: opacity 220ms ease;
}}

/* While generating it bobs, on top of the idle blink. */
body:has([data-streaming]) [data-composer-card]::after,
body:has([data-chat-flow-kind][data-streaming]) [data-composer-card]::after {{
  opacity: 1;
  animation: crab-bob 780ms ease-in-out infinite,
             crab-idle-frames 3s step-end infinite;
}}

/* The interactive crab (crab-plugin/) owns the composer position once it is
 * installed, because a pseudo-element cannot be clicked, focused or spoken to.
 * It sets this marker attribute; when present, the inert crab stands down so
 * there is exactly one Clawd. Without the plugin, this never matches and the
 * static crab remains the (non-interactive) fallback. */
/* Hide the inert crab ONLY when the interactive one is provably in the DOM.
 *
 * This deliberately does not key off a marker attribute the plugin sets: a
 * marker proves the plugin's apply() ran, not that its React occupant actually
 * rendered. A component that throws during render leaves the marker set and
 * the composer empty — the exact "no crab at all" failure that was observed.
 *
 * :has() on the real element is unfalsifiable: if .clawd3d exists, the skin
 * crab yields; if it does not, the skin crab stays. The plugin's own marker
 * is kept as a secondary hint but is no longer load-bearing. */
body:has(.dcc-crab) [data-composer-card]::after {{
  content: none;
}}

body[data-clawd-interactive] [data-composer-card]::after {{
  content: none;
}}

@keyframes crab-bob {{
  0%, 100% {{ translate: 0 0; }}
  50%      {{ translate: 0 -3px; }}
}}

/* Idle blink: eyes shut for ~5% of a 3s cycle, step-end so it snaps rather
   than interpolating between two pixel patterns (which would smear). */
@keyframes crab-idle-frames {{
  0%, 90%   {{ box-shadow: var(--crab-f-open); }}
  91%, 95%  {{ box-shadow: var(--crab-f-blink); }}
  96%, 100% {{ box-shadow: var(--crab-f-open); }}
}}

/* ---- B. Free-standing crab ------------------------------------------------
 * For an empty surface or a settings preview. Sized by --cl-crab-scale.
 * ------------------------------------------------------------------------- */
.cl-crab {{
  position: relative;
  display: inline-block;
  left: 0;
  top: 0;
  box-shadow: var(--crab-f-open);
  transform: scale(var(--cl-crab-scale, 1));
  animation: crab-blink 4.2s step-end infinite;
}}

/* Reserve the art's footprint so the element participates in layout. */
.cl-crab-box {{
  position: relative;
  display: inline-block;
  width: calc(var(--cl-crab-w) * var(--cl-crab-scale, 1));
  height: calc(var(--cl-crab-h) * var(--cl-crab-scale, 1));
}}

@keyframes crab-blink {{
  0%, 92%   {{ box-shadow: var(--crab-f-open); }}
  93%, 96%  {{ box-shadow: var(--crab-f-blink); }}
  97%, 100% {{ box-shadow: var(--crab-f-open); }}
}}

/* ---- C. Greeting particles ------------------------------------------------
 * The floating pixel sparkle beside the greeting, drawn the same way: one 3px
 * dot replicated by box-shadow.
 * ------------------------------------------------------------------------- */
[data-slot="conversation.hero.brand.mark"] {{
  position: relative;
}}

[data-slot="conversation.hero.brand.mark"]::after,
.cl-greeting-particles::after {{
  left: 0;
  top: 0;
  box-shadow:
    39px 0 0 var(--cl-crab-eye), 42px 0 0 var(--cl-crab-eye), 45px 0 0 var(--cl-crab-eye),
    45px 3px 0 var(--cl-crab-eye), 42px 6px 0 var(--cl-crab-eye),
    21px 12px 0 var(--cl-crab-eye), 27px 12px 0 var(--cl-crab-eye),
    33px 12px 0 var(--cl-crab-eye), 42px 12px 0 var(--cl-crab-eye);
  animation: crab-particle-float 2.83s cubic-bezier(.37,0,.22,1) .41s infinite;
}}

@keyframes crab-particle-float {{
  0%, 100% {{ transform: translateY(0);    opacity: .8; }}
  50%      {{ transform: translateY(-4px); opacity: 1; }}
}}

@media (prefers-reduced-motion: reduce) {{
  [data-composer-card]::after,
  .cl-crab-hero,
  .cl-greeting-particles {{ animation: none; }}
}}
"""

OUT.write_text(css, encoding='utf-8')
print(f"wrote {OUT} ({len(css)} bytes)")
print(f"frames ported: {len(blocks)}")

# The manifest only admits two stylesheets (stylesheet + patches), so the crab
# section is concatenated onto the hand-written selector layer to form the
# served patches.css. patches.base.css is the hand-written input; never edit
# patches.css directly.
base = ROOT / 'claude' / 'patches.base.css'
final = ROOT / 'claude' / 'patches.css'
final.write_text(base.read_text(encoding='utf-8').rstrip() + "\n\n" + css, encoding='utf-8')
print(f"composed {final} ({len(final.read_text(encoding='utf-8'))} bytes) = patches.base.css + crab")
